<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php 
    $data = $this->helper('Lof\MarketPlace\Helper\Data');
    $seller_id = $data->getSellerIdByProduct($block->getProduct()->getId());
    $seller = $data->getSeller($seller_id);
?>

<meta property="og:type" content="product" />
<meta property="og:title" content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($block->getProduct()))) ?> <?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getName())) ?>" />
<meta property="og:image" content="<?= $block->escapeUrl($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()) ?>" />
<meta property="og:description" content="<?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($block->getProduct()))) ?> <?= $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getName())); ?> for sale at OTR Tire Market by <?php echo $seller->getData('shop_title'); ?>" />
<meta property="og:url" content="<?= $block->escapeUrl($block->getProduct()->getProductUrl()) ?>" />
<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
    <meta property="product:price:amount" content="<?= /* @escapeNotVerified */ $priceAmount ?>"/>
    <?= $block->getChildHtml('meta.currency') ?>
<?php endif;?>





<!-- $block->escapeHtmlAttr($block->stripTags($block->getProduct()->getShortDescription())) -->
